name: lorenzetti-${TAG}
services:
  lorenzetti-base:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - GEANT4_VERSION=${GEANT4_VERSION}
        - PYTHIA8_VERSION=${PYTHIA8_VERSION}
        - FASTJET_VERSION=${FASTJET_VERSION}
        - HEPMC_VERSION=${HEPMC_VERSION}
        - ROOT_VERSION=${ROOT_VERSION}
    image: ${USERNAME}/lorenzetti:${TAG}
    container_name: lzt-container-${TAG}
    tty: true
