#!/usr/bin/env python3

from GaugiKernel import LoggingLevel
import argparse
import sys
from joblib import Parallel, delayed
from GaugiKernel import ComponentAccumulator
from RootStreamBuilder import RootStreamAODReader, recordable
from RootStreamBuilder import RootStreamNtupleMaker
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(description='', add_help=False)
    parser = argparse.ArgumentParser()

    parser.add_argument('-i', '--input-file', action='store',
                        dest='input_file', required=False,
                        help="The event input file generated by the"
                        " Pythia event generator.")

    parser.add_argument('-o', '--outputfile', action='store',
                        dest='output_file', required=False,
                        help="The reconstructed event file"
                        " generated by lzt/geant4 framework.")

    parser.add_argument('--nov', '--number-of-events', action='store',
                        dest='number_of_events', required=False, type=int,
                        default=-1,
                        help="The number of events to apply"
                        " the reconstruction.")

    parser.add_argument('-l', '--output-level', action='store',
                        dest='output_level', required=False,
                        type=str, default='INFO',
                        help="The output level messenger.")

    parser.add_argument('-nt', '--number-of-threads', action='store',
                        dest='number_of_threads', required=False,
                        type=int, default=1,
                        help="The number of threads")

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()
    args.input_file = Path(args.input_file)
    if not args.input_file.exists():
        raise FileNotFoundError(f"Input file {args.input_file} not found.")
    args.output_file = Path(args.output_file)

    return args


def main(output_level: str,
         output_file: str | Path,
         input_file: str | Path,
         number_of_events: int):

    if isinstance(output_file, Path):
        output_file = str(output_file)
    if isinstance(input_file, Path):
        input_file = str(input_file)

    outputLevel = LoggingLevel.fromstring(output_level)

    acc = ComponentAccumulator("ComponentAccumulator", output_file)
    aod = RootStreamAODReader("AODReader",
                              InputFile=input_file,
                              OutputLevel=outputLevel,
                              OutputEventKey=recordable("Events"),
                              OutputTruthKey=recordable("Particles"),
                              OutputClusterKey=recordable("Clusters"),
                              OutputRingerKey=recordable("Rings"),
                              OutputElectronKey=recordable("Electrons"),
                              OutputSeedsKey=recordable("Seeds"),
                              NtupleName="CollectionTree",
                              )
    aod.merge(acc)
    ntuple = RootStreamNtupleMaker("NtupleMaker",
                                   OutputLevel=outputLevel,
                                   InputEventKey=recordable("Events"),
                                   InputTruthKey=recordable("Particles"),
                                   InputClusterKey=recordable("Clusters"),
                                   InputRingerKey=recordable("Rings"),
                                   InputElectronKey=recordable("Electrons"),
                                   InputSeedsKey=recordable("Seeds"),
                                   OutputNtupleName="physics",
                                   )
    acc += ntuple
    acc.run(number_of_events)


def get_job_params(args):
    if args.input_file.is_dir():
        input_files = list(args.input_file.glob("*.root"))
    else:
        input_files = [args.input_file]

    splitted_output_filename = str(args.output_file).split(".")
    for i, input_file in enumerate(input_files):
        output_file = splitted_output_filename.copy()
        output_file.insert(-1, str(i))
        output_file = Path('.'.join(output_file))
        if output_file.exists():
            print(f"{i} - Output file {output_file} already exists. Skipping.")
            continue
        print(f"{i} - Output file {output_file} does not exist. Running.")
        yield input_file, output_file


if __name__ == "__main__":
    print('Starting execution of ntuple_trf.py')
    args = parse_args()
    print(f"Parsed args: {args.__dict__}")
    pool = Parallel(n_jobs=args.number_of_threads)
    pool(delayed(main)(
        output_level=args.output_level,
        input_file=input_file,
        output_file=output_file,
        number_of_events=args.number_of_events
    )
        for input_file, output_file in get_job_params(args))
    print('Finished execution of ntuple_trf.py')
